export const ActionTypes = {
  DATA_LOADING_START: 'change/DATA_LOADING_START',
  DATA_LOADING_END: 'change/DATA_LOADING_END',
  SEARCH_RESULTS: 'load/SEARCH_RESULTS',
  HISTORY_RESULTS: 'load/HISTORY_RESULTS',
  CITIIES_LIST: 'load/CITIIES_LIST',
  ERROR: 'change/ERROR',
};
