export const ActionTypes = {
  DATA_LOADING_START: 'change/DATA_LOADING_START',
  DATA_LOADING_END: 'change/DATA_LOADING_END',
  RESULTS_LOADING_START: 'change/RESULTS_LOADING_START',
  RESULTS_LOADING_END: 'change/RESULTS_LOADING_END',
  MENU_TYPE: 'change/MENU_TYPE',
  SEARCH_RESULTS: 'load/SEARCH_RESULTS',
  HISTORY_RESULTS: 'load/HISTORY_RESULTS',
  CITIIES_LIST: 'load/CITIIES_LIST',
  CITIIES_LIST_TO: 'load/CITIIES_LIST_TO',
  PRESELECTED_REQUEST: 'change/PRESELECTED_REQUEST',
  ERROR: 'change/ERROR',
};
